schema_version = "1.0.0"

id = "dolly_zoom"
version = "1.0.0"
name = "Dolly Zoom"
tagline = "Dolly zoom for viewport and camera"
maintainer = "Josef Ludvík Böhm"
type = "add-on"
documentation_url = "https://github.com/Surf-Ace/blender-dolly-zoom"
tags = ["3D View", "Camera"]
blender_version_min = "4.2.0"
license = ['SPDX:GPL-3.0-or-later']